// coverage:ignore-file

import 'package:drift/drift.dart';

/// Table definition to contain [Node] data.
///
/// The Column table is generated by Drift. Conversion from and to this class
/// should be handled by [NodeModel]. This class should only contain the column
/// definitions as it may get refactored in the future.
class DriftNodes extends Table {
  @override
  Set<Column> get primaryKey => {id};

  // Fields
  IntColumn get id => integer().nullable()();

  @JsonKey('node_type_id')
  IntColumn get nodeTypeId => integer()();

  IntColumn get parentId =>
      integer().nullable().customConstraint('REFERENCES drift_nodes (id)')();

  TextColumn get name => text()();

  TextColumn get description => text().nullable()();

  RealColumn get rating => real().nullable()();

  IntColumn get ratingsCount => integer().nullable()();

  TextColumn get breadcrumbs => text().nullable()();

  TextColumn get coverUrl => text().nullable()();

  IntColumn get createdAt => integer()();

  TextColumn get createdBy => text()();

  IntColumn get pointId => integer().nullable()();

  RealColumn get lat => real().nullable()();

  RealColumn get lng => real().nullable()();

  IntColumn? get updatedAt => integer().nullable()();

  TextColumn get updatedBy => text().nullable()();
}
